# Python Numpy tutorial

This tutorial is created to learn how to use Numpy package of python to handle arrays and matrices efficiently.

*******

*References*-
- [Python Numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/) by *Justin Johnson*.
- [NumPy Documentation](https://numpy.org/doc/)

In [1]:
import numpy as np

### Entering a 1-dimensional array-

In [2]:
array = np.array([1,2,3,4])

print(array)

[1 2 3 4]


In [3]:
array.shape

(4,)

### Entering a multi-dimensional array-

In [4]:
mul_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mul_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
mul_array.shape

(3, 3)

### Some functions to create matrices of several types-

In [10]:
zero_mat = np.zeros((3,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones_mat = np.ones((3,3))
print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
eye_mat = np.eye(3)                                  # Only one input unlike the previous ones
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
rand_mat = np.random.random((3,3))
print(rand_mat)

[[0.77880626 0.44473877 0.7494297 ]
 [0.00298136 0.93091491 0.17784188]
 [0.23216787 0.90343596 0.14279968]]


In [18]:
rand_int_mat = np.random.randint(10,size=(3,3))
print(rand_int_mat)

[[1 9 6]
 [4 0 8]
 [7 7 1]]


### Array slicing-

In [19]:
big_mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(big_mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [25]:
mat_1 = big_mat[:2,:2]
print(mat_1)

[[1 2]
 [5 6]]


In [28]:
mat_2 = big_mat[:2,2:4]
print(mat_2)

[[3 4]
 [7 8]]


In [29]:
mat_3 = big_mat[1:3,1:3]
print(mat_3)

[[ 6  7]
 [10 11]]


### Array Mathematics-

In [41]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print('x = ', x)
print('y = ', y)

x =  [[1 2]
 [3 4]]
y =  [[5 6]
 [7 8]]


In [31]:
print(x+y)

[[ 6  8]
 [10 12]]


In [32]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [33]:
print(np.subtract(y,x))

[[4 4]
 [4 4]]


In [34]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [35]:
print(np.divide(y,x))

[[5.         3.        ]
 [2.33333333 2.        ]]


Note that all the operations listed above were *element-wise* operations. We can also perform matrix-multiplication using the **dot()** function.

In [39]:
u = np.array([[1,2],[3,4]])
v = np.array([9,10])

print('u = ', u)
print('v = ', v)

u =  [[1 2]
 [3 4]]
v =  [ 9 10]


In [42]:
print(np.dot(u,v.T))

[29 67]
